language: ruby
rvm:
  - 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['API_SECRET'] %>
  run:
    - 'rake db:migrate'
  app: vulkan-group
  on:
    repo: netguru-training/vulkan-group
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
